#!/bin/bash -

# Rip Disc
# ========
#
# Lines common to rip-movie and rip-episodes.

## Variables

aspect_ratio=false
burn=true
add_aac=false
foreign=false
scan=false
use_TMDb=false
extra_displacement=0
constant_frame_rate=auto
subtitle_track="scan"
language="eng"
outputdir="$HOME/Movies"
prefix=""
season=1
extra_offset=1
source=""
preview_count=100
constant_fr=false
crop=auto

## Functions

_report_error () {
    printf "$(basename $0): $1.\n" >&2
    exit 1
}

_run() {
    if [[ -n "$dry_run" ]]; then
        echo "$@"
    else
        "$@"
    fi
}

_show_help() {
    printf -- "rip-movie [options] title\n"
    printf -- "rip-episodes [options] episode-list\n\n"
    printf -- "Options (and defaults):\n"
    printf -- "-5: enable decomb filter\n"
    printf -- "-a: instead of an AC3 track only, add AAC as the first track\n"
    printf -- "-b: don't burn subtitles into the video\n"
    printf -- "-c: constant_frame_rate: set the constant frame rate (${constant_frame_rate})\n"
    printf -- "-d: set the movie filename to its name and year using TMDb\n"
    printf -- "-e source: source VIDEO_TS or MakeMKV-created directory to rip the content from (${source})\n"
    printf -- "-f: assume a foreign film and include all subtitles, not just those that are forced\n"
    printf -- "-i displacement: displace the extras output file numbering (${extra_displacement})\n"
    printf -- "-l language: iso639-2 language to use for subtitles (and audio if not foreign) (${language})\n"
    printf -- "-m length: mimimum length (in mins) of titles to use (${min_length})\n"
    printf -- "-n: perform a dry run only\n"
    printf -- "-o dir: output directory (${outputdir})\n"
    printf -- "-p prefix: filename prefix ('${prefix}')\n"
    printf -- "-r pixel_aspect_ratio: colon-separated ratio (e.g., 16:9) (${aspect_ratio})\n"
    printf -- "-s n: season number (${season})\n"
    printf -- "-t n: start ripping extras from file offset n (${extra_offset})\n"
    printf -- "-u subtitle_track: subtitle track to rip (${subtitle_track})\n"
    printf -- "-v: override mediainfo and force constant framerate (${constant_fr})\n"
    printf -- "-w preview_count: how many previews to generate (can help with autocropping) (${preview_count})\n"
    printf -- "-x: Rip the disc extras\n"
    printf -- "-z crop: specify crop values <top:bottom:left:right> (${crop})\n"
    exit 2
}

_get_media_info() {
    # Detect source video properties with mediainfo
    media_info=$(mediainfo "$1")
    media_info_ar=$(grep -F 'Display aspect ratio' <<< "$media_info" | cut -d: -f2-)
    media_info_fm=$(grep -F 'Frame rate mode' <<< "$media_info" | cut -d: -f2-)
    media_info_fr=$(grep -F 'Frame rate' <<< "$media_info" | grep -vF mode | head -1 | cut -d: -f2- | cut -d' ' -f2)
    media_info_in=$(grep -F 'Scan type' <<< "$media_info" | cut -d: -f2-)
    media_info_ch=$(grep -F 'Channel(s)' <<< "$media_info" | cut -d: -f2-)
    media_info_he=$(grep -F 'Height' <<< "$media_info" | cut -d: -f2- | sed 's/[^0-9]//g')
}

_set_video_settings() {
    if [[ "$media_info_he" -ge 1080 ]]; then
        bitrate=6000
    elif [[ "$media_info_he" -ge 720 ]]; then
        bitrate=3000
    else
        bitrate=1500
    fi

    video_settings="--previews ${preview_count}:0 -e x264 -f mkv --modulus 2 -m --x264-preset medium --h264-profile high --h264-level 4.1 -q 1 -x vbv-maxrate=${bitrate}:vbv-bufsize=$((bitrate*2)):crf-max=25:qpmax=34 ${decomb} -N${language} --subtitle-default -s ${subtitle_track}"

    if ! "$foreign"; then
        # "Film isn't foreign, so find the forced subtitles only"
        video_settings="${video_settings} -F --native-dub"
    fi

    if [[ "$burn" == "true" ]]; then
        video_settings="${video_settings} --subtitle-burned"
    fi

    if [[ "$aspect_ratio" == "false" ]]; then
        video_settings="${video_settings} --auto-anamorphic"
    elif [[ "$aspect_ratio" == "auto" ]]; then
        video_settings="${video_settings} --custom-anamorphic --pixel-aspect ${media_info_ar}"
    else
        video_settings="${video_settings} --custom-anamorphic --pixel-aspect ${aspect_ratio}"
    fi

    if [[ "$constant_fr" == "false" ]]; then
        video_settings="${video_settings} --vfr"
    else
        if [[ "$constant_frame_rate" == "auto" ]]; then
            if grep -qF Constant <<< "$media_info_fm"; then
                video_settings="${video_settings} --cfr -r${media_info_fr}"
            else
                video_settings="${video_settings} --vfr"
            fi
        else
            video_settings="${video_settings} --cfr -r${constant_frame_rate}"
        fi
    fi

    if [[ "$crop" != "auto" ]]; then
        video_settings="${video_settings} --crop ${crop}"
    fi
}

_set_audio_settings() {
    audio_settings='-R Auto -D 0.0 --audio-fallback ac3'

    # If the film/episode isn't foreign, choose only the (default: English) audio track
    if ! "$foreign"; then
        audio_settings="${audio_settings} --audio-lang-list ${language}"
    fi

    # Use AAC codec if 2 channels are found for an audio stream and no 6 channel ones are
    if grep -qF 2 <<< "$media_info_ch" && ! grep -qF 6 <<< "$media_info_ch"; then
        audio_settings="${audio_settings} -6 dpl2 -E ca_aac -B 160"
    else
        if "$add_aac"; then
            audio_settings="${audio_settings} -6 dpl2,none -E ca_aac,copy:ac3 -B 160,640"
        else
            audio_settings="${audio_settings} -6 none -E copy:ac3 -B 640"
        fi
    fi
}

## Option parsing

while getopts :5abc:de:fi:l:m:no:p:r:s:t:u:vw:xz:h opt; do
    case "$opt" in
        5)    decomb="--comb-detect --decomb"
              ;;
        a)    add_aac=true
              ;;
        b)    burn=false
              ;;
        c)    constant_frame_rate="$OPTARG"
              ;;
        d)    use_TMDb=true
              ;;
        e)    source="$OPTARG"
              ;;
        f)    foreign=true
              ;;
        i)    extra_displacement="$OPTARG"
              ;;
        l)    language="$OPTARG"
              ;;
        m)    min_length="$OPTARG"
              ;;
        n)    dry_run=true
              ;;
        o)    outputdir="$OPTARG"
              ;;
        p)    prefix="$OPTARG"
              ;;
        r)    aspect_ratio="$OPTARG"
              ;;
        s)    season="$OPTARG"
              ;;
        t)    extra_offset="$OPTARG"
              ;;
        u)    subtitle_track="$OPTARG"
              ;;
        v)    constant_fr=true
              ;;
        w)    preview_count="$OPTARG"
              ;;
        x)    extras=true
              ;;
        z)    crop="$OPTARG"
              ;;
        h)    _show_help
              ;;
        '?')  _report_error "invalid option $OPTARG. Invoke with option -h for more info"
              ;;
    esac
done

shift $((OPTIND-1)) # Forget single-letter options now; put main options to front
