#!/usr/bin/env python

from os.path import expanduser
import re
import sys
import tmdbsimple as tmdb

def find_movie(movie, sort=False):
    """Return a tuple containing the movie title and year of release (empty if not found)."""

    with open(expanduser("~") + '/.tmdb_api_key', 'r') as file:
        tmdb.API_KEY = file.read().rstrip()

    search = tmdb.Search()
    response = search.movie(query=movie)
    if sort:
        results = sorted(response[u'results'], key=lambda k: k[u'popularity'], reverse=True)
    else:
        results = response[u'results']

    if len(results) > 0:
        first_movie = results[0]
        # Only allow common filesystem characters
        movie_title = re.sub(r"[^-a-zA-Z0-9.\(\)' ]", '', first_movie[u'title'])
        movie_year = re.search(r'(^\d+)', first_movie[u'release_date'])

        return movie_title, movie_year.group(0)

if __name__ == '__main__':
    movie = find_movie(sys.argv[1].replace('_', ' '))
    if movie:
        title=movie[0].encode('ascii', 'replace').decode('ascii')
        year=movie[1]
        print(title + ' (' + year + ')')
    else:
        sys.exit("find-movie: movie not found")
