#!/bin/bash -

# Rip Movie
# =========
#
# Rip a movie from a DVD using Handbrake.
#
# Pass the mkv source file as the first option. By default this will be the name of the
# written output file, in $outputdir.
#
# `rip-movie -h` for more.

source _rip-disc

## Main logic

inline_source="$*"

if [[ -n "$inline_source" ]]; then     # Specific movie name has been specified
    output_name="${inline_source}.mkv"
else                            # Take the basename of the source directory
    output_name=$(basename "$source").mkv
fi

if "$use_TMDb"; then
    output_name=$(find-movie "${output_name%.*}" 2>/dev/null).mkv

    if [[ $? -gt 0 ]]; then
        _report_error "movie name not found in TMDb"
    fi
fi

a_movie_files=("${source%/}"/*.mkv)
movie_file="${a_movie_files[0]}"

_get_media_info "$movie_file"

_set_video_settings

_set_audio_settings

if [[ -n $extras ]]; then
    mkdir -p "${outputdir}/${output_name%.mkv}/Extras"
    output_name="${output_name%.mkv}/${output_name}"
fi

_run HandBrakeCLI -i "$movie_file" -t1 -o "${outputdir}/${output_name}" ${video_settings} ${audio_settings}
